---

server:
  port: 8880

---

spring:
  profiles: hsql
  datasource:
    url: jdbc:hsqldb:mem:rentaltrucks
    username: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: hsql
    show-sql: true

context:
  initializer:
    classes: io.pivotal.pal.data.rentaltruck.BeansInitializer

---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:rentaltrucks;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: h2
    show-sql: true

context:
  initializer:
    classes: io.pivotal.pal.data.rentaltruck.BeansInitializer

---

spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost/kotlintrucks
    username: ${user.name}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false

context:
  initializer:
    classes: io.pivotal.pal.data.rentaltruck.BeansInitializer
